import { randomUUID } from "node:crypto";
import type { EmployeeAdministrationSummary, UpdateEmployeeAssignmentRequest, UUID } from "@teamzeit/contracts";
import { EmployeeAdministrationError, type AdministrationActor, type EmployeeAdministrationRepository, type InviteCommand } from "./administration.js";
export class InMemoryEmployeeAdministrationRepository implements EmployeeAdministrationRepository {
  private rows = new Map<UUID, EmployeeAdministrationSummary>();
  async list(organizationId: UUID) { void organizationId; return [...this.rows.values()]; }
  async create(actor: AdministrationActor, command: InviteCommand) { void actor; if ([...this.rows.values()].some(r => r.email === command.email)) throw new EmployeeAdministrationError("CONFLICT", "Für diese E-Mail besteht bereits eine Mitgliedschaft.", "email"); const row: EmployeeAdministrationSummary = { id: randomUUID(), email: command.email, role: command.role, status: "invited", version: 1 }; this.rows.set(row.id, row); return row; }
  async sendInvitation(actor: AdministrationActor, id: UUID, key: UUID) { void actor; void key; const row = this.rows.get(id); if (!row) throw new EmployeeAdministrationError("NOT_FOUND", "Mitgliedschaft nicht gefunden."); if (row.status !== "invited") throw new EmployeeAdministrationError("CONFLICT", "Nur eingeladene Mitarbeitende können eine Einladung erhalten."); const updated = { ...row, invitationSentAt: new Date().toISOString(), version: row.version + 1 }; this.rows.set(id, updated); return updated; }
  async invite(_actor: AdministrationActor, command: InviteCommand) { if ([...this.rows.values()].some(r => r.email === command.email)) throw new EmployeeAdministrationError("CONFLICT", "Für diese E-Mail besteht bereits eine Mitgliedschaft.", "email"); const row: EmployeeAdministrationSummary = { id: randomUUID(), email: command.email, role: command.role, status: "invited", version: 1, ...(command.teamId ? { teamId: command.teamId } : {}), ...(command.workPolicyId ? { workPolicyId: command.workPolicyId } : {}) }; this.rows.set(row.id, row); return row; }
  async deactivate(actor: AdministrationActor, id: UUID, version: number, key: UUID) { void actor; void key; const row = this.get(id, version); const updated = { ...row, status: "inactive" as const, version: version + 1 }; this.rows.set(id, updated); return updated; }
  async updateAssignment(actor: AdministrationActor, id: UUID, command: UpdateEmployeeAssignmentRequest, key: UUID) { void actor; void key; const row = this.get(id, command.expectedVersion); const updated: EmployeeAdministrationSummary = { ...row, ...(command.role ? { role: command.role } : {}), teamId: command.teamId === null ? undefined : command.teamId ?? row.teamId, workPolicyId: command.workPolicyId === null ? undefined : command.workPolicyId ?? row.workPolicyId, version: row.version + 1 }; this.rows.set(id, updated); return updated; }
  private get(id: UUID, version: number) { const row = this.rows.get(id); if (!row) throw new EmployeeAdministrationError("NOT_FOUND", "Mitgliedschaft nicht gefunden."); if (row.version !== version) throw new EmployeeAdministrationError("CONFLICT", "Die Mitgliedschaft wurde zwischenzeitlich geändert.", "expectedVersion"); return row; }
}
