import type { MonthClosureDto } from "@teamzeit/contracts";
import type { SupabaseClient } from "@supabase/supabase-js";
import { TimeTrackingError } from "../time-tracking/errors.js";
import type { MonthClosingCommand, MonthClosingRepository } from "./types.js";
interface Result<T> { data: T | null; error: { message: string } | null; } interface Row { id: string; organization_id: string; membership_id: string; month_start: string; closed_at: string; closed_by_membership_id: string; reopened_at: string | null; reopened_by_membership_id: string | null; reason: string | null; }
interface Builder<T> extends PromiseLike<Result<T[]>> { select(columns: string): Builder<T>; eq(column: string, value: string): Builder<T>; maybeSingle(): Promise<Result<T>>; } interface Client { from<T>(table: string): Builder<T>; rpc<T>(fn: string, args: Record<string, unknown>): Promise<Result<T>>; }
const columns = "id, organization_id, membership_id, month_start, closed_at, closed_by_membership_id, reopened_at, reopened_by_membership_id, reason";
export class PostgresMonthClosingRepository implements MonthClosingRepository {
  private readonly client: Client; public constructor(client: SupabaseClient) { this.client = client as unknown as Client; }
  public async get(organizationId: string, membershipId: string, monthStart: string) { const result = await this.client.from<Row>("month_closures").select(columns).eq("organization_id", organizationId).eq("membership_id", membershipId).eq("month_start", monthStart).maybeSingle(); if (result.error) throw new TimeTrackingError("INTERNAL_ERROR", "Der Monatsabschluss konnte nicht geladen werden."); return result.data ? map(result.data) : undefined; }
  public close(command: MonthClosingCommand) { return this.apply("close", command); } public reopen(command: MonthClosingCommand) { return this.apply("reopen", command); }
  private async apply(operation: "close" | "reopen", command: MonthClosingCommand): Promise<MonthClosureDto> { const result = await this.client.rpc<Row>("month_closing_apply", { operation, target_organization_id: command.organizationId, actor_membership_id: command.membershipId, actor_user_id: command.userId, target_membership_id: command.targetMembershipId, target_month_start: command.monthStart, command_reason: command.reason, command_request_id: command.requestId, command_occurred_at: command.occurredAt }); if (result.error) throw mapError(result.error.message); if (!result.data) throw new TimeTrackingError("INTERNAL_ERROR", "Der Monatsabschluss wurde nicht gespeichert."); return map(result.data); }
}
function map(row: Row): MonthClosureDto { return { id: row.id, organizationId: row.organization_id, membershipId: row.membership_id, monthStart: row.month_start, status: row.reopened_at ? "open" : "closed", closedAt: row.closed_at, closedByMembershipId: row.closed_by_membership_id, ...(row.reopened_at ? { reopenedAt: row.reopened_at } : {}), ...(row.reopened_by_membership_id ? { reopenedByMembershipId: row.reopened_by_membership_id } : {}), ...(row.reason ? { reason: row.reason } : {}) }; }
function mapError(message: string): TimeTrackingError { if (message.includes("forbidden")) return new TimeTrackingError("FORBIDDEN", "Nur Administratoren dürfen Monate schließen oder öffnen."); if (message.includes("target_not_found")) return new TimeTrackingError("NOT_FOUND", "Die Mitgliedschaft wurde nicht gefunden."); if (message.includes("already_closed") || message.includes("already_open")) return new TimeTrackingError("CONFLICT", message.includes("already_closed") ? "Der Monat ist bereits geschlossen." : "Der Monat ist bereits geöffnet."); if (message.includes("validation")) return new TimeTrackingError("VALIDATION_ERROR", "Die Abschlussdaten sind ungültig."); return new TimeTrackingError("INTERNAL_ERROR", "Der Monatsabschluss konnte nicht gespeichert werden."); }
