import type { EmployeeAdministrationSummary, MembershipRole, WeekdayMinutes } from "@teamzeit/contracts";
import { type FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useAuth } from "../auth/AuthProvider";
import { createEmployee, listEmployees, sendEmployeeInvitation, setEmployeeWorkRule, updateEmployee } from "../employees/api";

const defaultMinutes: WeekdayMinutes = { monday: 480, tuesday: 480, wednesday: 480, thursday: 480, friday: 480, saturday: 0, sunday: 0 };
const weekdays: [keyof WeekdayMinutes, string][] = [["monday","Mo"],["tuesday","Di"],["wednesday","Mi"],["thursday","Do"],["friday","Fr"],["saturday","Sa"],["sunday","So"]];
const today = () => new Date().toISOString().slice(0, 10);

export function EmployeesPage() {
  const { session, activeMembership } = useAuth();
  const [items, setItems] = useState<EmployeeAdministrationSummary[]>([]); const [selectedId, setSelectedId] = useState<string>();
  const [error, setError] = useState<string>(); const [success, setSuccess] = useState<string>(); const [pending, setPending] = useState(false);
  const context = useMemo(() => session && activeMembership ? { accessToken: session.access_token, organizationId: activeMembership.organization.id } : null, [session, activeMembership]);
  const selected = items.find((item) => item.id === selectedId);
  const load = useCallback(async () => { if (!context) return; try { const result = await listEmployees(context); setItems(result); setSelectedId((current) => current ?? result[0]?.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Mitarbeitende konnten nicht geladen werden."); } }, [context]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function run(action: () => Promise<unknown>, message: string) { setPending(true); setError(undefined); try { await action(); setSuccess(message); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Die Änderung konnte nicht gespeichert werden."); } finally { setPending(false); } }
  function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!context) return; const data = new FormData(event.currentTarget); void run(async () => { const row = await createEmployee(context, { email: String(data.get("email")), role: String(data.get("role")) as Exclude<MembershipRole,"owner"> }); setSelectedId(row.id); }, "Mitarbeiter wurde angelegt."); event.currentTarget.reset(); }
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!context || !selected) return; const data = new FormData(event.currentTarget); const weekdayMinutes = Object.fromEntries(weekdays.map(([key]) => [key, Math.round(Number(data.get(key)) * 60)])) as unknown as WeekdayMinutes; void run(async () => { await updateEmployee(context, selected.id, { role: String(data.get("role")) as MembershipRole, expectedVersion: selected.version }); await setEmployeeWorkRule(context, selected.id, { effectiveFrom: String(data.get("effectiveFrom")), weekdayMinutes }); }, "Mitarbeiter und Arbeitszeit wurden gespeichert."); }
  return <section className="attendance-page" aria-labelledby="employees-title"><div className="page-heading"><p className="eyebrow">Organisation</p><h1 id="employees-title">Mitarbeitende</h1><p className="page-intro">Profile, Zugänge und Arbeitszeiten gemeinsam verwalten.</p></div>{error && <p className="error-note" role="alert">{error}</p>}{success && <p className="success-note">{success}</p>}<div className="employee-admin-grid">
    <section className="panel"><h2>Neuer Mitarbeiter</h2><form className="employee-form" onSubmit={create}><label>E-Mail<input name="email" type="email" required /></label><label>Rolle<select name="role" defaultValue="employee"><option value="employee">Mitarbeiter</option><option value="manager">Vorgesetzter</option><option value="admin">Administrator</option><option value="auditor">Prüfer</option></select></label><button className="primary-button" disabled={pending}>Mitarbeiter anlegen</button></form><div className="employee-list">{items.map((item) => <button key={item.id} className={`employee-card${item.id === selectedId ? " selected" : ""}`} onClick={() => setSelectedId(item.id)}><strong>{item.email}</strong><span>{item.role} · {item.status}</span></button>)}</div></section>
    <section className="panel">{selected ? <><div className="panel-header"><div><p className="eyebrow">Mitarbeiter</p><h2>{selected.email}</h2></div><span className="state-pill state-completed">{selected.status}</span></div><form className="employee-form" onSubmit={save}><label>Rolle<select name="role" defaultValue={selected.role}><option value="employee">Mitarbeiter</option><option value="manager">Vorgesetzter</option><option value="admin">Administrator</option><option value="auditor">Prüfer</option></select></label><label>Gültig ab<input name="effectiveFrom" type="date" defaultValue={today()} required /></label><fieldset><legend>Geplante Stunden pro Tag</legend><div className="weekday-grid">{weekdays.map(([key,label]) => <label key={key}>{label}<input name={key} type="number" min="0" max="24" step="0.25" defaultValue={defaultMinutes[key] / 60} required /></label>)}</div></fieldset><p className="hint-text">Bei mehr als 6 Stunden werden mindestens 30 Minuten Pause berücksichtigt.</p><button className="primary-button" disabled={pending}>Änderungen speichern</button></form>{selected.status === "invited" && <button className="secondary-button" disabled={pending} onClick={() => context && void run(() => sendEmployeeInvitation(context, selected.id), "Einladung wurde gesendet.")}>{selected.invitationSentAt ? "Einladung erneut senden" : "Einladung senden"}</button>}</> : <div className="empty-state"><p>Wähle einen Mitarbeiter aus.</p></div>}</section>
  </div></section>;
}
