/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/month-closures/{membershipId}/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMonthClosure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/month-closures/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["closeMonth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/month-closures/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reopenMonth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEmployees"];
        put?: never;
        post: operations["createEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{membershipId}/invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendEmployeeInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inviteEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{membershipId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deactivateEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{membershipId}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateEmployeeAssignment"];
        trace?: never;
    };
    "/attendance/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTodayAttendance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/days/{workDate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDailyAttendance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/months/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMonthlyAttendance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/employees/{membershipId}/work-rule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEmployeeWorkRule"];
        put: operations["setEmployeeWorkRule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/commands/clock-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clockIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/commands/clock-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clockOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/commands/break-start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["deprecatedBreakStartAsClockOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/commands/break-end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["deprecatedBreakEndAsClockIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOwnIntervals"];
        put?: never;
        post: operations["createOwnInterval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/attendance/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["monthlyAttendanceReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateOwnInterval"];
        post?: never;
        delete: operations["archiveOwnInterval"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisation-structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrganisationStructure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisation-structure/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisation-structure/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisation-structure/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setTeamAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisation-structure/manager-scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setManagerScope"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/absences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAbsences"];
        put?: never;
        post: operations["createAbsence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/absences/{absenceId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reviewAbsence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/absences/{absenceId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelAbsence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateAbsence: {
            /** @enum {string} */
            type: "vacation" | "sickness" | "other";
            /** Format: date */
            startsOn: string;
            /** Format: date */
            endsOn: string;
            employeeNote?: string;
        };
        ReviewAbsence: {
            /** @enum {string} */
            decision: "approved" | "rejected";
            reviewNote?: string;
            expectedVersion: number;
        };
        AbsenceRequest: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            membershipId: string;
            /** @enum {string} */
            type: "vacation" | "sickness" | "other";
            /** Format: date */
            startsOn: string;
            /** Format: date */
            endsOn: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "cancelled";
            employeeNote?: string;
            reviewNote?: string;
            /** Format: uuid */
            reviewedByMembershipId?: string;
            /** Format: date-time */
            reviewedAt?: string;
            /** Format: date-time */
            createdAt: string;
            version: number;
        };
        AbsenceList: {
            items: components["schemas"]["AbsenceRequest"][];
        };
        NamedStructure: {
            name: string;
            /** Format: uuid */
            locationId?: string | null;
        };
        TeamAssignment: {
            /** Format: uuid */
            membershipId: string;
            /** Format: uuid */
            teamId: string;
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validUntil?: string | null;
            /** @default true */
            primary?: boolean;
        };
        ManagerScope: {
            /** Format: uuid */
            managerMembershipId: string;
            /** @enum {string} */
            scopeType: "location" | "team";
            /** Format: uuid */
            locationId?: string;
            /** Format: uuid */
            teamId?: string;
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validUntil?: string | null;
        };
        OrganisationStructure: {
            locations: components["schemas"]["Location"][];
            teams: components["schemas"]["Team"][];
            assignments: components["schemas"]["TeamAssignmentDto"][];
            managerScopes: components["schemas"]["ManagerScopeDto"][];
        };
        Location: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            name: string;
            /** Format: date-time */
            archivedAt?: string;
        };
        Team: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            locationId?: string;
            name: string;
            /** Format: date-time */
            archivedAt?: string;
        };
        TeamAssignmentDto: {
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            teamId: string;
            /** Format: uuid */
            membershipId: string;
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validUntil?: string;
            primary: boolean;
        };
        ManagerScopeDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            managerMembershipId: string;
            /** @enum {string} */
            scopeType: "location" | "team";
            /** Format: uuid */
            locationId?: string;
            /** Format: uuid */
            teamId?: string;
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validUntil?: string;
        };
        MonthClosureCommand: {
            /** Format: uuid */
            membershipId: string;
            month: string;
            reason: string;
        };
        InviteEmployee: {
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "admin" | "manager" | "employee" | "auditor";
            /** Format: uuid */
            teamId?: string;
            /** Format: uuid */
            workPolicyId?: string;
        };
        CreateEmployee: {
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "admin" | "manager" | "employee" | "auditor";
        };
        WorkSession: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            membershipId: string;
            /** Format: date */
            workDate: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt?: string;
            breaks: components["schemas"]["WorkBreak"][];
            workedMinutes?: number;
            /** Format: date-time */
            calculationEndedAt?: string;
            /** @enum {string} */
            issue?: "missing_clock_out";
            /** @enum {string} */
            state: "not_started" | "working" | "completed" | "requires_action";
            /** @enum {string} */
            source: "clock" | "manual" | "admin_import";
            version: number;
        };
        WorkBreak: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt?: string;
            durationMinutes?: number;
        };
        CreateInterval: {
            /** Format: date */
            workDate: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string;
        };
        UpdateInterval: components["schemas"]["CreateInterval"] & {
            expectedVersion: number;
        };
        SetEmployeeWorkRule: {
            /** Format: date */
            effectiveFrom: string;
            weekdayMinutes: {
                monday: number;
                tuesday: number;
                wednesday: number;
                thursday: number;
                friday: number;
                saturday: number;
                sunday: number;
            };
            /** @default 360 */
            breakThresholdMinutes?: number;
            /** @default 30 */
            minimumBreakMinutes?: number;
        };
        EmployeeWorkRule: components["schemas"]["SetEmployeeWorkRule"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            membershipId: string;
            /** Format: date */
            effectiveTo?: string;
            breakThresholdMinutes: number;
            minimumBreakMinutes: number;
        };
        EmployeeWorkRuleResponse: {
            rule?: components["schemas"]["EmployeeWorkRule"];
        };
        DailyAttendance: {
            /** Format: date */
            workDate: string;
            /** @enum {string} */
            state: "not_started" | "working" | "completed" | "requires_action";
            sessions: components["schemas"]["WorkSession"][];
            workedMinutes: number;
            breakMinutes: number;
            recordedBreakMinutes: number;
            automaticBreakMinutes: number;
            plannedMinutes: number;
            balanceMinutes: number;
            isHoliday: boolean;
            requiresAction: boolean;
        };
        TodayAttendance: components["schemas"]["DailyAttendance"] & {
            /** Format: date-time */
            serverTime: string;
            activeSession?: components["schemas"]["WorkSession"];
        };
        MonthlyAttendance: {
            month: string;
            days: components["schemas"]["DailyAttendance"][];
            workedMinutes: number;
            breakMinutes: number;
            plannedMinutes: number;
            balanceMinutes: number;
            requiresAction: boolean;
        };
        MonthlyAttendanceReportRow: {
            /** Format: uuid */
            membershipId: string;
            /** Format: email */
            email: string;
            workedMinutes: number;
            sessionCount: number;
            daysWorked: number;
            openSessionCount: number;
        };
        MonthlyAttendanceReportTotals: {
            workedMinutes: number;
            sessionCount: number;
            daysWorked: number;
            openSessionCount: number;
        };
        MonthlyAttendanceReport: {
            /** Format: uuid */
            organizationId: string;
            month: string;
            rows: components["schemas"]["MonthlyAttendanceReportRow"][];
            totals: components["schemas"]["MonthlyAttendanceReportTotals"];
        };
    };
    responses: {
        /** @description Server-time clock result */
        ClockCommand: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** Format: date-time */
                    serverTime: string;
                    session: components["schemas"]["WorkSession"];
                };
            };
        };
        /** @description Active tenant membership or ownership missing */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Invalid state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        /** @description Tenant selector verified against the authenticated membership. */
        OrganizationId: string;
        IdempotencyKey: string;
        SessionId: string;
        MembershipId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMonthClosure: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
            };
            path: {
                membershipId: components["parameters"]["MembershipId"];
                month: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current open or closed status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    closeMonth: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthClosureCommand"];
            };
        };
        responses: {
            /** @description Month closed and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    reopenMonth: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthClosureCommand"];
            };
        };
        responses: {
            /** @description Month reopened and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listEmployees: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant employee administration list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createEmployee: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployee"];
            };
        };
        responses: {
            /** @description Invited employee record created without sending an invitation */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    sendEmployeeInvitation: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                membershipId: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation sent or resent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    inviteEmployee: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteEmployee"];
            };
        };
        responses: {
            /** @description Invitation and invited membership created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    deactivateEmployee: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                membershipId: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membership deactivated and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    updateEmployeeAssignment: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                membershipId: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getTodayAttendance: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current day including intervals and derived totals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayAttendance"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getDailyAttendance: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
            };
            path: {
                workDate: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily interval overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyAttendance"];
                };
            };
        };
    };
    getMonthlyAttendance: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
            };
            path: {
                month: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monthly totals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyAttendance"];
                };
            };
        };
    };
    getEmployeeWorkRule: {
        parameters: {
            query: {
                on: string;
            };
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
            };
            path: {
                membershipId: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective work rule or an empty object when no rule exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeWorkRuleResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    setEmployeeWorkRule: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                membershipId: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetEmployeeWorkRule"];
            };
        };
        responses: {
            /** @description Effective-dated employee work rule created and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    clockIn: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ClockCommand"];
            409: components["responses"]["Conflict"];
        };
    };
    clockOut: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ClockCommand"];
            409: components["responses"]["Conflict"];
        };
    };
    deprecatedBreakStartAsClockOut: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ClockCommand"];
        };
    };
    deprecatedBreakEndAsClockIn: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ClockCommand"];
        };
    };
    listOwnIntervals: {
        parameters: {
            query: {
                /** @description Inclusive start date */
                from: string;
                /** @description Inclusive end date; must not precede from and the range is limited to 366 days */
                to: string;
            };
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Own intervals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createOwnInterval: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInterval"];
            };
        };
        responses: {
            /** @description Interval created immediately */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkSession"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    monthlyAttendanceReport: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
            };
            path: {
                month: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scope-aware monthly attendance report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyAttendanceReport"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    updateOwnInterval: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInterval"];
            };
        };
        responses: {
            /** @description Interval updated immediately */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    archiveOwnInterval: {
        parameters: {
            query: {
                expectedVersion: number;
            };
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Interval archived immediately */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    getOrganisationStructure: {
        parameters: {
            query?: {
                on?: string;
            };
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Date-effective structure visible to the actor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationStructure"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createLocation: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamedStructure"];
            };
        };
        responses: {
            /** @description Location created and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamedStructure"];
            };
        };
        responses: {
            /** @description Team created and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    setTeamAssignment: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamAssignment"];
            };
        };
        responses: {
            /** @description Effective assignment created and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    setManagerScope: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManagerScope"];
            };
        };
        responses: {
            /** @description Effective manager scope created and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listAbsences: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorised absence requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbsenceList"];
                };
            };
        };
    };
    createAbsence: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAbsence"];
            };
        };
        responses: {
            /** @description Request created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbsenceRequest"];
                };
            };
        };
    };
    reviewAbsence: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                absenceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewAbsence"];
            };
        };
        responses: {
            /** @description Scoped request reviewed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelAbsence: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant selector verified against the authenticated membership. */
                "X-Organization-Id": components["parameters"]["OrganizationId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                absenceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedVersion: number;
                };
            };
        };
        responses: {
            /** @description Pending own request cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
